dbfilename redis_queue.rdb
dir /home/emlad/Developer/frappe-crm-f0rk/frappe-bench/config/pids
pidfile /home/emlad/Developer/frappe-crm-f0rk/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/emlad/Developer/frappe-crm-f0rk/frappe-bench/config/redis_queue.acl
